// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: kvi.proto

package kvi_grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	mi := &file_kvi_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kvi_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_kvi_proto_rawDescGZIP(), []int{0}
}

func (x *GetRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type GetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	DataJson      string                 `protobuf:"bytes,2,opt,name=data_json,json=dataJson,proto3" json:"data_json,omitempty"` // JSON representation for dynamic map
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResponse) Reset() {
	*x = GetResponse{}
	mi := &file_kvi_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResponse) ProtoMessage() {}

func (x *GetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kvi_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResponse.ProtoReflect.Descriptor instead.
func (*GetResponse) Descriptor() ([]byte, []int) {
	return file_kvi_proto_rawDescGZIP(), []int{1}
}

func (x *GetResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetResponse) GetDataJson() string {
	if x != nil {
		return x.DataJson
	}
	return ""
}

type PutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	DataJson      string                 `protobuf:"bytes,2,opt,name=data_json,json=dataJson,proto3" json:"data_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutRequest) Reset() {
	*x = PutRequest{}
	mi := &file_kvi_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutRequest) ProtoMessage() {}

func (x *PutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kvi_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutRequest.ProtoReflect.Descriptor instead.
func (*PutRequest) Descriptor() ([]byte, []int) {
	return file_kvi_proto_rawDescGZIP(), []int{2}
}

func (x *PutRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *PutRequest) GetDataJson() string {
	if x != nil {
		return x.DataJson
	}
	return ""
}

type PutResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutResponse) Reset() {
	*x = PutResponse{}
	mi := &file_kvi_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutResponse) ProtoMessage() {}

func (x *PutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kvi_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutResponse.ProtoReflect.Descriptor instead.
func (*PutResponse) Descriptor() ([]byte, []int) {
	return file_kvi_proto_rawDescGZIP(), []int{3}
}

func (x *PutResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type VectorSearchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vector        []float32              `protobuf:"fixed32,1,rep,packed,name=vector,proto3" json:"vector,omitempty"`
	K             int32                  `protobuf:"varint,2,opt,name=k,proto3" json:"k,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VectorSearchRequest) Reset() {
	*x = VectorSearchRequest{}
	mi := &file_kvi_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VectorSearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VectorSearchRequest) ProtoMessage() {}

func (x *VectorSearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kvi_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VectorSearchRequest.ProtoReflect.Descriptor instead.
func (*VectorSearchRequest) Descriptor() ([]byte, []int) {
	return file_kvi_proto_rawDescGZIP(), []int{4}
}

func (x *VectorSearchRequest) GetVector() []float32 {
	if x != nil {
		return x.Vector
	}
	return nil
}

func (x *VectorSearchRequest) GetK() int32 {
	if x != nil {
		return x.K
	}
	return 0
}

type VectorSearchResponse struct {
	state         protoimpl.MessageState         `protogen:"open.v1"`
	Results       []*VectorSearchResponse_Result `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VectorSearchResponse) Reset() {
	*x = VectorSearchResponse{}
	mi := &file_kvi_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VectorSearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VectorSearchResponse) ProtoMessage() {}

func (x *VectorSearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kvi_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VectorSearchResponse.ProtoReflect.Descriptor instead.
func (*VectorSearchResponse) Descriptor() ([]byte, []int) {
	return file_kvi_proto_rawDescGZIP(), []int{5}
}

func (x *VectorSearchResponse) GetResults() []*VectorSearchResponse_Result {
	if x != nil {
		return x.Results
	}
	return nil
}

type StreamRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                                               // client id
	Channel        string                 `protobuf:"bytes,2,opt,name=channel,proto3" json:"channel,omitempty"`                                     // subscribe channel
	PublishPayload string                 `protobuf:"bytes,3,opt,name=publish_payload,json=publishPayload,proto3" json:"publish_payload,omitempty"` // if sending a message
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *StreamRequest) Reset() {
	*x = StreamRequest{}
	mi := &file_kvi_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamRequest) ProtoMessage() {}

func (x *StreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kvi_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamRequest.ProtoReflect.Descriptor instead.
func (*StreamRequest) Descriptor() ([]byte, []int) {
	return file_kvi_proto_rawDescGZIP(), []int{6}
}

func (x *StreamRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *StreamRequest) GetChannel() string {
	if x != nil {
		return x.Channel
	}
	return ""
}

func (x *StreamRequest) GetPublishPayload() string {
	if x != nil {
		return x.PublishPayload
	}
	return ""
}

type StreamResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Channel       string                 `protobuf:"bytes,1,opt,name=channel,proto3" json:"channel,omitempty"`
	Payload       string                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamResponse) Reset() {
	*x = StreamResponse{}
	mi := &file_kvi_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamResponse) ProtoMessage() {}

func (x *StreamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kvi_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamResponse.ProtoReflect.Descriptor instead.
func (*StreamResponse) Descriptor() ([]byte, []int) {
	return file_kvi_proto_rawDescGZIP(), []int{7}
}

func (x *StreamResponse) GetChannel() string {
	if x != nil {
		return x.Channel
	}
	return ""
}

func (x *StreamResponse) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

type VectorSearchResponse_Result struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	DataJson      string                 `protobuf:"bytes,2,opt,name=data_json,json=dataJson,proto3" json:"data_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VectorSearchResponse_Result) Reset() {
	*x = VectorSearchResponse_Result{}
	mi := &file_kvi_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VectorSearchResponse_Result) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VectorSearchResponse_Result) ProtoMessage() {}

func (x *VectorSearchResponse_Result) ProtoReflect() protoreflect.Message {
	mi := &file_kvi_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VectorSearchResponse_Result.ProtoReflect.Descriptor instead.
func (*VectorSearchResponse_Result) Descriptor() ([]byte, []int) {
	return file_kvi_proto_rawDescGZIP(), []int{5, 0}
}

func (x *VectorSearchResponse_Result) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *VectorSearchResponse_Result) GetDataJson() string {
	if x != nil {
		return x.DataJson
	}
	return ""
}

var File_kvi_proto protoreflect.FileDescriptor

const file_kvi_proto_rawDesc = "" +
	"\n" +
	"\tkvi.proto\x12\x03kvi\"\x1e\n" +
	"\n" +
	"GetRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\":\n" +
	"\vGetResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tdata_json\x18\x02 \x01(\tR\bdataJson\";\n" +
	"\n" +
	"PutRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x1b\n" +
	"\tdata_json\x18\x02 \x01(\tR\bdataJson\"'\n" +
	"\vPutResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\";\n" +
	"\x13VectorSearchRequest\x12\x16\n" +
	"\x06vector\x18\x01 \x03(\x02R\x06vector\x12\f\n" +
	"\x01k\x18\x02 \x01(\x05R\x01k\"\x89\x01\n" +
	"\x14VectorSearchResponse\x12:\n" +
	"\aresults\x18\x01 \x03(\v2 .kvi.VectorSearchResponse.ResultR\aresults\x1a5\n" +
	"\x06Result\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tdata_json\x18\x02 \x01(\tR\bdataJson\"b\n" +
	"\rStreamRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\achannel\x18\x02 \x01(\tR\achannel\x12'\n" +
	"\x0fpublish_payload\x18\x03 \x01(\tR\x0epublishPayload\"D\n" +
	"\x0eStreamResponse\x12\x18\n" +
	"\achannel\x18\x01 \x01(\tR\achannel\x12\x18\n" +
	"\apayload\x18\x02 \x01(\tR\apayload2\xdc\x01\n" +
	"\n" +
	"KviService\x12(\n" +
	"\x03Get\x12\x0f.kvi.GetRequest\x1a\x10.kvi.GetResponse\x12(\n" +
	"\x03Put\x12\x0f.kvi.PutRequest\x1a\x10.kvi.PutResponse\x12C\n" +
	"\fVectorSearch\x12\x18.kvi.VectorSearchRequest\x1a\x19.kvi.VectorSearchResponse\x125\n" +
	"\x06Stream\x12\x12.kvi.StreamRequest\x1a\x13.kvi.StreamResponse(\x010\x01B-Z+github.com/thirawat27/kvi/pkg/grpc;kvi_grpcb\x06proto3"

var (
	file_kvi_proto_rawDescOnce sync.Once
	file_kvi_proto_rawDescData []byte
)

func file_kvi_proto_rawDescGZIP() []byte {
	file_kvi_proto_rawDescOnce.Do(func() {
		file_kvi_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_kvi_proto_rawDesc), len(file_kvi_proto_rawDesc)))
	})
	return file_kvi_proto_rawDescData
}

var file_kvi_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_kvi_proto_goTypes = []any{
	(*GetRequest)(nil),                  // 0: kvi.GetRequest
	(*GetResponse)(nil),                 // 1: kvi.GetResponse
	(*PutRequest)(nil),                  // 2: kvi.PutRequest
	(*PutResponse)(nil),                 // 3: kvi.PutResponse
	(*VectorSearchRequest)(nil),         // 4: kvi.VectorSearchRequest
	(*VectorSearchResponse)(nil),        // 5: kvi.VectorSearchResponse
	(*StreamRequest)(nil),               // 6: kvi.StreamRequest
	(*StreamResponse)(nil),              // 7: kvi.StreamResponse
	(*VectorSearchResponse_Result)(nil), // 8: kvi.VectorSearchResponse.Result
}
var file_kvi_proto_depIdxs = []int32{
	8, // 0: kvi.VectorSearchResponse.results:type_name -> kvi.VectorSearchResponse.Result
	0, // 1: kvi.KviService.Get:input_type -> kvi.GetRequest
	2, // 2: kvi.KviService.Put:input_type -> kvi.PutRequest
	4, // 3: kvi.KviService.VectorSearch:input_type -> kvi.VectorSearchRequest
	6, // 4: kvi.KviService.Stream:input_type -> kvi.StreamRequest
	1, // 5: kvi.KviService.Get:output_type -> kvi.GetResponse
	3, // 6: kvi.KviService.Put:output_type -> kvi.PutResponse
	5, // 7: kvi.KviService.VectorSearch:output_type -> kvi.VectorSearchResponse
	7, // 8: kvi.KviService.Stream:output_type -> kvi.StreamResponse
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_kvi_proto_init() }
func file_kvi_proto_init() {
	if File_kvi_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_kvi_proto_rawDesc), len(file_kvi_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_kvi_proto_goTypes,
		DependencyIndexes: file_kvi_proto_depIdxs,
		MessageInfos:      file_kvi_proto_msgTypes,
	}.Build()
	File_kvi_proto = out.File
	file_kvi_proto_goTypes = nil
	file_kvi_proto_depIdxs = nil
}
